[phases.setup]
nixPkgs = ["php", "phpPackages.composer"]

[phases.install]
cmds = [
    "composer install --ignore-platform-reqs --no-dev --optimize-autoloader",
    "chmod +x start.sh"
]

[phases.build]
cmds = []

[start]
cmd = "./start.sh" 