name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - azure_deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: omarabdelazeem/nostalgia:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- OPTIONAL: AZURE DEPLOYMENT ---
      # To enable auto-deployment to Azure App Service, uncomment the following steps
      # and add the required secrets to your GitHub repository.
      #
      # Required Secrets:
      # 1. AZURE_CREDENTIALS: A JSON object containing the credentials of a service principal.
      #    - Generate with: `az ad sp create-for-rbac --name "nostalgia-api-deploy" --role contributor --scopes /subscriptions/{subscription-id}/resourceGroups/nostalgia-app --sdk-auth`
      # 2. AZURE_WEBAPP_NAME: The name of your Azure Web App (e.g., "nostalgia-api").
      #
      # - name: Log in to Azure
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      #
      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v3
      #   with:
      #     app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
      #     images: 'omarabdelazeem/nostalgia:latest'
